### ISSUE TITLE
bedgraph -bga

### ISSUE THREAD

**Issue by mgalland** [KoesGroup/DMC1_ChIPseq#4]
Hello Jihed, 
About the pull request #3:
Why do you want to report regions with zero coverage (`bedtools genomecov -bga`)? Is there a specific reason? Because this will significantly increase the size of your bedgraph files. 
I think you could simply use the `-bg`option there and only report the positions with some coverage. 
Hope it helps,
Cheers
Marc

**Comment by JihedC** [comment]
Hi Marc,
I didn't give it so much thought to be honest. As I would like to see also coldspot of recombination I thought that if I can observe some locations showing significantly more 0 coverage than others it would be interesting. 
But I am not sure this is what I get with `-bga`

**Comment by mgalland** [comment]
Ok. Let's discuss it and maybe update the Snakefile accordingly.
